version: '3'
services:
  wifi-vendor:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    ports:
      - '80:80'

  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/dbData:/var/lib/mysql
    ports:
      - '3306:3306'
